# Generated by Django 2.2.1 on 2020-04-17 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mooc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='编号')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('institute', models.CharField(max_length=128, verbose_name='机构')),
                ('hard', models.CharField(max_length=32, verbose_name='难度')),
                ('class_hour', models.IntegerField(verbose_name='学时')),
                ('hot', models.IntegerField(verbose_name='热度')),
                ('language', models.CharField(max_length=128, verbose_name='语言')),
                ('start_time', models.CharField(max_length=128, verbose_name='开课日期')),
                ('subheading', models.CharField(max_length=128, verbose_name='副标题')),
                ('sump', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('pic', models.FileField(max_length=64, upload_to='mooc_cover', verbose_name='封面图片')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.IntegerField(default=0, verbose_name='用户数量')),
                ('moocs', models.IntegerField(default=0, verbose_name='课程数量')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数量')),
                ('rates', models.IntegerField(default=0, verbose_name='评分汇总')),
                ('actions', models.IntegerField(default=0, verbose_name='活动汇总')),
                ('message_boards', models.IntegerField(default=0, verbose_name='留言汇总')),
            ],
            options={
                'verbose_name': '数据统计',
                'verbose_name_plural': '数据统计',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名字')),
                ('address', models.CharField(max_length=32, verbose_name='地址')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(verbose_name='评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('mooc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Mooc', verbose_name='课程id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '评分信息',
                'verbose_name_plural': '评分信息',
            },
        ),
        migrations.AddField(
            model_name='mooc',
            name='collect',
            field=models.ManyToManyField(blank=True, to='user.User', verbose_name='收藏者'),
        ),
        migrations.AddField(
            model_name='mooc',
            name='tags',
            field=models.ManyToManyField(blank=True, to='user.Tags', verbose_name='学科'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('good', models.IntegerField(default=0, verbose_name='点赞')),
                ('mooc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Mooc', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
